/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets a list of all available categories. OData filtering is supported, e.g. $filter=name eq 'march'. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                    /** @description Free text search across archive number, title, composer and arranger. */
                    $search?: string;
                    /** @description OData filter expression, for example "title eq 'Fanfare'" or "archiveNumber gt 100". */
                    $filter?: string;
                    /** @description Comma separated sort clauses on the format "field [asc|desc]", for example "composer asc,title desc". */
                    $orderby?: string;
                    /** @description Maximum number of rows to return. Must be at least 1. */
                    $top?: number;
                    /** @description Number of rows to skip before returning results. */
                    $skip?: number;
                    /** @description Comma separated list of related collections to include, for example "parts". */
                    $expand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of categories matching filter, or all categories. Empty list if no matching results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Adds a new category.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Details about the new category */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryRequest"];
                    "text/json": components["schemas"]["CategoryRequest"];
                    "application/*+json": components["schemas"]["CategoryRequest"];
                };
            };
            responses: {
                /** @description Details about the newly created category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets details about the category identified by categoryIdentifier. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the category. Either guid or name */
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The category matching the identifier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        /**
         * Updates the category identified by categoryIdentifier.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the category. Either guid or name */
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            /** @description Updated details for the category */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryRequest"];
                    "text/json": components["schemas"]["CategoryRequest"];
                    "application/*+json": components["schemas"]["CategoryRequest"];
                };
            };
            responses: {
                /** @description The updated category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Deletes the category identified by categoryIdentifier.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the category. Either guid or name */
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets complete list of sheet music sets, optionally expanding parts or projects, or the ones matching queryParams.Search.Search if provided.
         *     Use ZipDownloadUrl for complete parts download and PartsUrl to list parts.
         */
        get: {
            parameters: {
                query: {
                    /** @description Optional. Filter sets by category, identified by guid or name */
                    category?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                    /** @description Free text search across archive number, title, composer and arranger. */
                    $search?: string;
                    /** @description OData filter expression, for example "title eq 'Fanfare'" or "archiveNumber gt 100". */
                    $filter?: string;
                    /** @description Comma separated sort clauses on the format "field [asc|desc]", for example "composer asc,title desc". */
                    $orderby?: string;
                    /** @description Maximum number of rows to return. Must be at least 1. */
                    $top?: number;
                    /** @description Number of rows to skip before returning results. */
                    $skip?: number;
                    /** @description Comma separated list of related collections to include, for example "parts". */
                    $expand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of sets matching filter, or all sets. Empty list if no matching results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Adds a new set to the list (without parts).
         *     ID, number and scanned is optional. Number will be next in sequence if not specified.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Information about the new set */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description The newly created set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists parts for set with identifier */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Set information including its parts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single part for a set */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                    /** @description A value uniquely identifying part. Either guid or part name */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The part matching the identifiers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSheetMusicPart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Deletes the PDF content and the relationship for partIdentifier of set with setIdentifier. */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                    /** @description Name of the part to add */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 204 if successfull, 404 if not found, 500 if something bad happens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the PDF file for set with setIdentifier, part with partIdentifier */
        get: {
            parameters: {
                query: {
                    /** @description A token to prove you are authorized for download */
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                    /** @description A value uniquely identifying part. Either guid or part name */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The PDF file content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets information about a single set, either by guid, number or title. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The set matching the identifier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        /** Updates information about a set. PS! All properties will be updated, omitted once are nulled out. */
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            /** @description Update set parameters */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description The updated set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes the set with setIdentifier, including all the parts and files */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Set was deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Asks the sheet-music agent a question about a set identified by its name. */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The request cancellation token. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetAgentQuestionRequest"];
                    "text/json": components["schemas"]["SetAgentQuestionRequest"];
                    "application/*+json": components["schemas"]["SetAgentQuestionRequest"];
                };
            };
            responses: {
                /** @description The agent response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSetAgentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the categories assigned to set with setIdentifier */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of categories assigned to the set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        put?: never;
        /** Assigns a category to set with setIdentifier */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            /** @description The category to assign, identified by guid or name */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignCategoryRequest"];
                    "text/json": components["schemas"]["AssignCategoryRequest"];
                    "application/*+json": components["schemas"]["AssignCategoryRequest"];
                };
            };
            responses: {
                /** @description The updated list of categories assigned to the set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/categories/{categoryIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a category from set with setIdentifier */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                    /** @description A value uniquely identifying category. Either guid or name */
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 204 if successfull, 404 if set, category or the assignment was not found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorized a set for download, allowing a single download for the one with the token. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The generated download token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the part collection for a set as a zip file.
         *     Accepts anonymous requests, but they must provide a download token that is validated to be able to download.
         */
        get: {
            parameters: {
                query: {
                    /** @description A token for proving that user is allowed to download this set */
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The zipped collection of parts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/withoutFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyzes the assigned parts and compares them with the blob storage content.
         *     If a non-empty file does not exists, the set is listed in results
         */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The sets with parts that are assigned, but a file is not present */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload all parts for set with identifier identifier as zip file */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    identifier: string;
                };
                cookie?: never;
            };
            /** @description Cancellation token for the upload operation. */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description Parts were uploaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds the PDF content for partIdentifier of set with setIdentifier. */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying set. Either guid, archive number or title */
                    setIdentifier: string;
                    /** @description Name of the part to add */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            /** @description The PDF file for the part */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description Part content was added successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets a list of all projects. OData filtering is supported, e.g. $filter=name eq 'Christmas concert'. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                    /** @description Free text search across archive number, title, composer and arranger. */
                    $search?: string;
                    /** @description OData filter expression, for example "title eq 'Fanfare'" or "archiveNumber gt 100". */
                    $filter?: string;
                    /** @description Comma separated sort clauses on the format "field [asc|desc]", for example "composer asc,title desc". */
                    $orderby?: string;
                    /** @description Maximum number of rows to return. Must be at least 1. */
                    $top?: number;
                    /** @description Number of rows to skip before returning results. */
                    $skip?: number;
                    /** @description Comma separated list of related collections to include, for example "parts". */
                    $expand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of projects matching filter, or all projects. Empty list if no matching results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProject"][];
                        "application/json": components["schemas"]["ApiProject"][];
                        "text/json": components["schemas"]["ApiProject"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Adds a new project.
         *     Requires Noteansvarlig, Prosjektleder or Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Details about the new project */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewProjectRequest"];
                    "text/json": components["schemas"]["NewProjectRequest"];
                    "application/*+json": components["schemas"]["NewProjectRequest"];
                };
            };
            responses: {
                /** @description Details about the newly created project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProject"];
                        "application/json": components["schemas"]["ApiProject"];
                        "text/json": components["schemas"]["ApiProject"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets details about the project identified by projectIdentifier. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The project matching the identifier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProject"];
                        "application/json": components["schemas"]["ApiProject"];
                        "text/json": components["schemas"]["ApiProject"];
                    };
                };
            };
        };
        /**
         * Updates the project identified by projectIdentifier. PS! Provide all values, those not provided will be set to null.
         *     Requires Noteansvarlig, Prosjektleder or Administrator privileges.
         */
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            /** @description Updated details for the project */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                    "text/json": components["schemas"]["UpdateProjectRequest"];
                    "application/*+json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description The updated project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProject"];
                        "application/json": components["schemas"]["ApiProject"];
                        "text/json": components["schemas"]["ApiProject"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes the project identified by projectIdentifier. */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the sets assigned to the project identified by projectIdentifier. */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of sets assigned to the project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiSet"][];
                        "application/json": components["schemas"]["ApiSet"][];
                        "text/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Assigns the given sets to a project. The order of List&lt;string&gt; SetCollectionRequest.SetIdentifiers determines
         *     the sort order of those sets - sets already assigned to the project are moved to match their position in the
         *     list, so this endpoint also covers reordering the sets currently assigned to a project.
         *     Requires Noteansvarlig, Prosjektleder or Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            /** @description The identifiers (guid, archive number or title) of the sets to assign, in the desired order */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiSet"][];
                        "application/json": components["schemas"]["ApiSet"][];
                        "text/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        /**
         * Removes the given sets from a project.
         *     Requires Noteansvarlig, Prosjektleder or Administrator privileges.
         */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description A value uniquely identifying the project. Either guid or name */
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            /** @description The identifiers (guid, archive number or title) of the sets to unassign */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description The updated list of sets assigned to the project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiSet"][];
                        "application/json": components["schemas"]["ApiSet"][];
                        "text/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for a part through the Part index.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        get: {
            parameters: {
                query: {
                    /** @description The search term to use when searching */
                    searchTerm?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The best match for the part */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Rebuild the part index manually.
         *     Whenever a change is done that requires rebuild, a rebuild is triggered.
         *     This needn't be invoked unless you did some manual changes in the database.
         *     Requires Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets a list of all Parts. OData filtering is supported, e.g. $filter=name eq 'partitur'.
         *     Use $expand=aliases to include the enabled aliases of each part.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                    /** @description Free text search across archive number, title, composer and arranger. */
                    $search?: string;
                    /** @description OData filter expression, for example "title eq 'Fanfare'" or "archiveNumber gt 100". */
                    $filter?: string;
                    /** @description Comma separated sort clauses on the format "field [asc|desc]", for example "composer asc,title desc". */
                    $orderby?: string;
                    /** @description Maximum number of rows to return. Must be at least 1. */
                    $top?: number;
                    /** @description Number of rows to skip before returning results. */
                    $skip?: number;
                    /** @description Comma separated list of related collections to include, for example "parts". */
                    $expand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of parts matching filter, or all parts. Empty list if no matching results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a new part.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Details about the new part */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description Details about the newly created part */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets details about part identified by partIdentifier.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description Identifier (name, alias or Guid) of the part */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Part information including list of aliases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        /**
         * Updates information about part identified by partIdentifier PS! Provide all values, those not provided will be set to null.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description Identifier (name, alias or Guid) of the part */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            /** @description Request body containing all properties */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description Updated part information including list of aliases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Deletes part identified by partIdentifier permanently.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description Identifier (name, alias or Guid) of the part. Case insensitive for part names. */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adds alias to part identified by partIdentifier.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        post: {
            parameters: {
                query: {
                    /** @description An alias the part is also known as */
                    alias?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description Identifier (name, alias or Guid) of the part */
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated part information including list of aliases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete alias from part identified by partIdentifier.
         *     Requires Noteansvarlig or Administrator privileges.
         */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    /** @description Identifier (name, alias or Guid) of the part */
                    partIdentifier: string;
                    /** @description An alias the part is also known as */
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated part information including list of aliases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiCategory: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            inactive?: boolean;
        };
        ApiPart: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            sortOrder?: number | string;
            indexable?: boolean;
            instrumentGroup?: null | components["schemas"]["InstrumentGroup"];
            aliases?: string[];
        };
        ApiProject: {
            /** Format: uuid */
            id?: string;
            name?: string;
            comments?: null | string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        /** @description A project summary included in an expanded sheet music set. */
        ApiProjectSummary: {
            /**
             * Format: uuid
             * @description Identifier in the database.
             */
            id?: string;
            /** @description Project name. */
            name?: string;
            /**
             * Format: date-time
             * @description Project start date.
             */
            startDate?: string;
            /**
             * Format: date-time
             * @description Project end date.
             */
            endDate?: string;
        };
        ApiSet: {
            /**
             * Format: uuid
             * @description Identifier in DB
             */
            id?: string;
            /**
             * Format: int32
             * @description Number in physical archive
             */
            archiveNumber?: number | string;
            title?: null | string;
            composer?: null | string;
            arranger?: null | string;
            soleSellingAgent?: null | string;
            missingParts?: null | string;
            recordingUrl?: null | string;
            hasBeenScanned?: boolean;
            borrowed?: boolean;
            borrowedFrom?: null | string;
            /** Format: date-time */
            borrowedDateTime?: null | string;
            /** @description Download pdf of parts for set on this URL */
            zipDownloadUrl?: string;
            /** @description List parts of set on this URL */
            partsUrl?: string;
            /** @description A list of parts for the set, if included */
            parts?: null | components["schemas"]["ApiSheetMusicPart"][];
            /** @description The projects connected to the set, if included */
            projects?: null | components["schemas"]["ApiProjectSummary"][];
            /** @description The categories assigned to this set */
            categories?: components["schemas"]["ApiCategory"][];
        };
        ApiSetAgentResponse: {
            answer: null | string;
        };
        ApiSheetMusicPart: {
            /** Format: uuid */
            relationshipId?: string;
            /** Format: uuid */
            setId?: string;
            /** Format: uuid */
            musicPartId?: string;
            name?: string;
            aliases?: null | string;
            pdfDownloadUrl?: null | string;
            deletePartUrl?: null | string;
        };
        AssignCategoryRequest: {
            /** @description Identifier (guid or name) of the category to assign */
            categoryIdentifier?: string;
        };
        CategoryRequest: {
            name?: string;
            inactive?: null | boolean;
        };
        ExpressionType: number;
        /** Format: binary */
        IFormFile: string;
        /** @enum {unknown} */
        InstrumentGroup: "Kornett" | "Horn og flygelhorn" | "Euphonium og baryton" | "Tromboner" | "Tuba" | "Slagverk" | null;
        NewProjectRequest: {
            name?: string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            comments?: null | string;
        };
        ODataExpression: {
            type?: components["schemas"]["ExpressionType"];
        };
        ODataOrderByOption: {
            field?: string;
            direction?: components["schemas"]["SortDirection"];
        };
        ODataQueryParams: {
            /** Format: int32 */
            $top?: null | number | string;
            /** Format: int32 */
            $skip?: null | number | string;
            $orderBy?: components["schemas"]["ODataOrderByOption"][];
            $filter?: null | components["schemas"]["ODataExpression"];
            $search?: null | string;
            $expand?: string[];
            hasFilter?: boolean;
            hasSearch?: boolean;
            isEmpty?: boolean;
        };
        PartRequest: {
            name?: string;
            /** Format: int32 */
            sortOrder?: number | string;
            indexable?: null | boolean;
            instrumentGroup?: null | components["schemas"]["InstrumentGroup"];
        };
        SetAgentQuestionRequest: {
            setName?: string;
            question?: string;
        };
        SetCollectionRequest: {
            setIdentifiers?: string[];
        };
        SetRequest: {
            /** Format: int32 */
            archiveNumber?: null | number | string;
            title?: string;
            composer?: null | string;
            recordingUrl?: null | string;
            arranger?: null | string;
            soleSellingAgent?: null | string;
            missingParts?: null | string;
            borrowedFrom?: null | string;
        };
        SortDirection: number;
        UpdateProjectRequest: {
            name?: string;
            comments?: null | string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
