/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pdf/singleSplit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf/smartSplit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    queryParams?: components["schemas"]["ODataQueryParams"];
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSheetMusicPart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/withoutFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "2.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiSet: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            archiveNumber?: number;
            title?: string | null;
            composer?: string | null;
            arranger?: string | null;
            soleSellingAgent?: string | null;
            missingParts?: string | null;
            recordingUrl?: string | null;
            hasBeenScanned?: boolean;
            readonly borrowed?: boolean;
            borrowedFrom?: string | null;
            /** Format: date-time */
            borrowedDateTime?: string | null;
            zipDownloadUrl?: string | null;
            partsUrl?: string | null;
            parts?: components["schemas"]["ApiSheetMusicPart"][] | null;
        };
        ApiSheetMusicPart: {
            /** Format: uuid */
            relationshipId?: string;
            /** Format: uuid */
            setId?: string;
            /** Format: uuid */
            musicPartId?: string;
            name?: string | null;
            aliases?: string | null;
            pdfDownloadUrl?: string | null;
            deletePartUrl?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ExpressionType: 0 | 1;
        ODataExpression: {
            type?: components["schemas"]["ExpressionType"];
        };
        ODataOrderByOption: {
            field?: string | null;
            direction?: components["schemas"]["SortDirection"];
        };
        ODataQueryParams: {
            /** Format: int32 */
            $top?: number | null;
            /** Format: int32 */
            $skip?: number | null;
            $orderBy?: components["schemas"]["ODataOrderByOption"][] | null;
            $filter?: components["schemas"]["ODataExpression"];
            $search?: string | null;
            $expand?: string[] | null;
            readonly hasFilter?: boolean;
            readonly hasSearch?: boolean;
            readonly isEmpty?: boolean;
        };
        SetRequest: {
            /** Format: int32 */
            archiveNumber?: number | null;
            title?: string | null;
            composer?: string | null;
            recordingUrl?: string | null;
            arranger?: string | null;
            soleSellingAgent?: string | null;
            missingParts?: string | null;
            borrowedFrom?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SortDirection: 0 | 1;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
