/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Top?: number;
                    Skip?: number;
                    OrderBy?: components["schemas"]["ODataOrderByOption"][];
                    "Filter.Type"?: components["schemas"]["ExpressionType"];
                    Search?: string;
                    Expand?: string[];
                    HasFilter?: boolean;
                    HasSearch?: boolean;
                    IsEmpty?: boolean;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategoryRequest"];
                    "text/json": components["schemas"]["CategoryRequest"];
                    "application/*+json": components["schemas"]["CategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategoryRequest"];
                    "text/json": components["schemas"]["CategoryRequest"];
                    "application/*+json": components["schemas"]["CategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    searchTerm?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Top?: number;
                    Skip?: number;
                    OrderBy?: components["schemas"]["ODataOrderByOption"][];
                    "Filter.Type"?: components["schemas"]["ExpressionType"];
                    Search?: string;
                    Expand?: string[];
                    HasFilter?: boolean;
                    HasSearch?: boolean;
                    IsEmpty?: boolean;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    alias?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Top?: number;
                    Skip?: number;
                    OrderBy?: components["schemas"]["ODataOrderByOption"][];
                    "Filter.Type"?: components["schemas"]["ExpressionType"];
                    Search?: string;
                    Expand?: string[];
                    HasFilter?: boolean;
                    HasSearch?: boolean;
                    IsEmpty?: boolean;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["NewProjectRequest"];
                    "text/json": components["schemas"]["NewProjectRequest"];
                    "application/*+json": components["schemas"]["NewProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                    "text/json": components["schemas"]["UpdateProjectRequest"];
                    "application/*+json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    queryParams?: components["schemas"]["ODataQueryParams"];
                    category?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSheetMusicPart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AssignCategoryRequest"];
                    "text/json": components["schemas"]["AssignCategoryRequest"];
                    "application/*+json": components["schemas"]["AssignCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiCategory"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/categories/{categoryIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    categoryIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/withoutFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        grant_type?: string;
                        username?: string;
                        password?: string;
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiAccessTokens"];
                        "application/json": components["schemas"]["ApiAccessTokens"];
                        "text/json": components["schemas"]["ApiAccessTokens"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                    "text/json": components["schemas"]["UserRequest"];
                    "application/*+json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiAccessTokens: {
            access_token?: null | string;
            refresh_token?: null | string;
            token_type?: null | string;
            /** Format: int32 */
            expires_in?: number;
            scope?: null | string;
        };
        ApiCategory: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            inactive?: boolean;
        };
        ApiPart: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            /** Format: int32 */
            sortOrder?: number;
            indexable?: boolean;
            aliases?: null | string[];
        };
        ApiSet: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            archiveNumber?: number;
            title?: null | string;
            composer?: null | string;
            arranger?: null | string;
            soleSellingAgent?: null | string;
            missingParts?: null | string;
            recordingUrl?: null | string;
            hasBeenScanned?: boolean;
            readonly borrowed?: boolean;
            borrowedFrom?: null | string;
            /** Format: date-time */
            borrowedDateTime?: null | string;
            zipDownloadUrl?: null | string;
            partsUrl?: null | string;
            parts?: null | components["schemas"]["ApiSheetMusicPart"][];
            categories?: null | components["schemas"]["ApiCategory"][];
        };
        ApiSheetMusicPart: {
            /** Format: uuid */
            relationshipId?: string;
            /** Format: uuid */
            setId?: string;
            /** Format: uuid */
            musicPartId?: string;
            name?: null | string;
            aliases?: null | string;
            pdfDownloadUrl?: null | string;
            deletePartUrl?: null | string;
        };
        AssignCategoryRequest: {
            categoryIdentifier?: null | string;
        };
        CategoryRequest: {
            name?: null | string;
            inactive?: null | boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ExpressionType: 0 | 1;
        NewProjectRequest: {
            name?: null | string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            comments?: null | string;
        };
        ODataExpression: {
            type?: components["schemas"]["ExpressionType"];
        };
        ODataOrderByOption: {
            field?: null | string;
            direction?: components["schemas"]["SortDirection"];
        };
        ODataQueryParams: {
            /** Format: int32 */
            $top?: null | number;
            /** Format: int32 */
            $skip?: null | number;
            $orderBy?: null | components["schemas"]["ODataOrderByOption"][];
            $filter?: components["schemas"]["ODataExpression"];
            $search?: null | string;
            $expand?: null | string[];
            readonly hasFilter?: boolean;
            readonly hasSearch?: boolean;
            readonly isEmpty?: boolean;
        };
        PartRequest: {
            name?: null | string;
            /** Format: int32 */
            sortOrder?: number;
            indexable?: null | boolean;
        };
        SetCollectionRequest: {
            setIdentifiers?: null | string[];
        };
        SetRequest: {
            /** Format: int32 */
            archiveNumber?: null | number;
            title?: null | string;
            composer?: null | string;
            recordingUrl?: null | string;
            arranger?: null | string;
            soleSellingAgent?: null | string;
            missingParts?: null | string;
            borrowedFrom?: null | string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SortDirection: 0 | 1;
        UpdateProjectRequest: {
            name?: null | string;
            comments?: null | string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        UpdateUserRequest: {
            name?: null | string;
            email?: null | string;
            password?: null | string;
        };
        UserRequest: {
            /** Format: uuid */
            id?: null | string;
            name?: null | string;
            email?: null | string;
            password?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
