/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/parts/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    searchTerm?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Top?: number;
                    Skip?: number;
                    OrderBy?: components["schemas"]["ODataOrderByOption"][];
                    "Filter.Type"?: components["schemas"]["ExpressionType"];
                    Search?: string;
                    Expand?: string[];
                    HasFilter?: boolean;
                    HasSearch?: boolean;
                    IsEmpty?: boolean;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartRequest"];
                    "text/json": components["schemas"]["PartRequest"];
                    "application/*+json": components["schemas"]["PartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    alias?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{partIdentifier}/aliases/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    partIdentifier: string;
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiPart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf/singleSplit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf/smartSplit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Top?: number;
                    Skip?: number;
                    OrderBy?: components["schemas"]["ODataOrderByOption"][];
                    "Filter.Type"?: components["schemas"]["ExpressionType"];
                    Search?: string;
                    Expand?: string[];
                    HasFilter?: boolean;
                    HasSearch?: boolean;
                    IsEmpty?: boolean;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["NewProjectRequest"];
                    "text/json": components["schemas"]["NewProjectRequest"];
                    "application/*+json": components["schemas"]["NewProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                    "text/json": components["schemas"]["UpdateProjectRequest"];
                    "application/*+json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectIdentifier}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    projectIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetCollectionRequest"];
                    "text/json": components["schemas"]["SetCollectionRequest"];
                    "application/*+json": components["schemas"]["SetCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    queryParams?: components["schemas"]["ODataQueryParams"];
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"][];
                    };
                };
            };
        };
        put?: never;
        /** @deprecated */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSheetMusicPart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @deprecated */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        /** @deprecated */
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetRequest"];
                    "text/json": components["schemas"]["SetRequest"];
                    "application/*+json": components["schemas"]["SetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSet"];
                    };
                };
            };
        };
        post?: never;
        /** @deprecated */
        delete: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    downloadToken?: string;
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/withoutFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheetmusic/sets/{setIdentifier}/parts/{partIdentifier}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    setIdentifier: string;
                    partIdentifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        grant_type?: string;
                        username?: string;
                        password?: string;
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiAccessTokens"];
                        "application/json": components["schemas"]["ApiAccessTokens"];
                        "text/json": components["schemas"]["ApiAccessTokens"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                    "text/json": components["schemas"]["UserRequest"];
                    "application/*+json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description The requested API version */
                    "api-version": "1.0";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiAccessTokens: {
            access_token?: string | null;
            refresh_token?: string | null;
            token_type?: string | null;
            /** Format: int32 */
            expires_in?: number;
            scope?: string | null;
        };
        ApiPart: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            indexable?: boolean;
            aliases?: string[] | null;
        };
        ApiSet: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            archiveNumber?: number;
            title?: string | null;
            composer?: string | null;
            arranger?: string | null;
            soleSellingAgent?: string | null;
            missingParts?: string | null;
            recordingUrl?: string | null;
            hasBeenScanned?: boolean;
            readonly borrowed?: boolean;
            borrowedFrom?: string | null;
            /** Format: date-time */
            borrowedDateTime?: string | null;
            zipDownloadUrl?: string | null;
            partsUrl?: string | null;
            parts?: components["schemas"]["ApiSheetMusicPart"][] | null;
        };
        ApiSheetMusicPart: {
            /** Format: uuid */
            relationshipId?: string;
            /** Format: uuid */
            setId?: string;
            /** Format: uuid */
            musicPartId?: string;
            name?: string | null;
            aliases?: string | null;
            pdfDownloadUrl?: string | null;
            deletePartUrl?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ExpressionType: 0 | 1;
        NewProjectRequest: {
            name?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        ODataExpression: {
            type?: components["schemas"]["ExpressionType"];
        };
        ODataOrderByOption: {
            field?: string | null;
            direction?: components["schemas"]["SortDirection"];
        };
        ODataQueryParams: {
            /** Format: int32 */
            $top?: number | null;
            /** Format: int32 */
            $skip?: number | null;
            $orderBy?: components["schemas"]["ODataOrderByOption"][] | null;
            $filter?: components["schemas"]["ODataExpression"];
            $search?: string | null;
            $expand?: string[] | null;
            readonly hasFilter?: boolean;
            readonly hasSearch?: boolean;
            readonly isEmpty?: boolean;
        };
        PartRequest: {
            name?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            indexable?: boolean | null;
        };
        SetCollectionRequest: {
            setIdentifiers?: string[] | null;
        };
        SetRequest: {
            /** Format: int32 */
            archiveNumber?: number | null;
            title?: string | null;
            composer?: string | null;
            recordingUrl?: string | null;
            arranger?: string | null;
            soleSellingAgent?: string | null;
            missingParts?: string | null;
            borrowedFrom?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SortDirection: 0 | 1;
        UpdateProjectRequest: {
            name?: string | null;
            comments?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        UpdateUserRequest: {
            name?: string | null;
            email?: string | null;
            password?: string | null;
        };
        UserRequest: {
            /** Format: uuid */
            id?: string | null;
            name?: string | null;
            email?: string | null;
            password?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
