# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages: 
- stage: BuildAndDeployToTest
  displayName: Build and publish to Test
  variables:
  - name: SVELTE_APP_API_URL
    value: 'https://sheet-music-api-test.azurewebsites.net'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      displayName: 'Package files into .zip archive'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/public'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - deployment: DeployTest
    dependsOn: Build
    condition: succeeded()
    environment: 'App test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy package to SheetMusic Admin'
            inputs:
              azureSubscription: 'Visual Studio Professional(8ba210c5-c187-44bb-9d0b-858282bb4487)'
              appType: 'webAppLinux'
              appName: 'sheetmusic-app-test'
              package: '$(Pipeline.Workspace)/**/$(Build.BuildId).zip'
              runtimeStack: 'NODE|12-lts'

- stage: BuildAndDeployToProduction
  displayName: Build and deploy to production
  variables:
  - name: SVELTE_APP_API_URL
    value: 'https://sheetmusic-api.azurewebsites.net'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      displayName: 'Package files into .zip archive'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/public'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  - deployment: DeployProd
    environment: 'App production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy package to SheetMusic Admin'
            inputs:
              azureSubscription: 'Visual Studio Professional(8ba210c5-c187-44bb-9d0b-858282bb4487)'
              appType: 'webAppLinux'
              appName: 'sheetmusic-app'
              package: '$(Pipeline.Workspace)/**/$(Build.BuildId).zip'
              runtimeStack: 'NODE|12-lts'